### ISSUE TITLE
Unable to create Authzforce Policies

### ISSUE THREAD

**Issue by jason-fox** [ging/fiware-idm#50]
With the following docker compose, 

```yml
  keyrock:
    image: fiware/idm
    container_name: fiware-keyrock
    hostname: keyrock
    depends_on:
      - mysql-db
      - authzforce
    ports:
      - "3005:3005"
    environment:
      - IDM_PDP_LEVEL=advanced
      - IDM_AUTHZFORCE_ENABLED=true
      - IDM_AUTHZFORCE_HOST=authzforce
      - IDM_AUTHZFORCE_PORT=8080
    secrets:                
      - my_secret_data

  authzforce:
    image: fiware/authzforce-ce-server
    hostname: authzforce
    container_name: fiware-authzforce
    ports: 
      - "8080:8080"
```

When updating an application's roles and permissions, the policies are not sent to **Authzforce**.

The Debug log states:

```
Connection with Authzforce: 200
...
web-authzforce_controller DOMAIN OF APPLICATION IS: gQqnLOnIEeiBFQJCrBIBDA
web-authzforce_controller POLICY ID: f8194af5-8a07-486a-9581-c1f05d05483c
web-authzforce_controller VERSION OF POLICY: 1
web-authzforce_controller RESPONSE CODE FROM POLICY ACTIVATION: 406
web-authzforce_controller Authzforce activate policy: error
```
