### ISSUE TITLE
Docker image doesn't work

### ISSUE THREAD

**Issue by RiosQ** [ging/fiware-idm#6]
i'm trying to dockerize the new version of keyrock in a project in progress . I have all components in a docker compose file but the file suggested here, presents this error:

```
Unable to connect to the database:  { SequelizeConnectionError: Host '172.18.1.6' is not allowed to connect to this MySQL server
```

**Comment by apozohue10** [comment]
Hi @RiosQ 

In the docker-compose.yml file you need to set MYSQL_ROOT_HOST with the IP of the IdM container instead of its name. It seems that mysql container do not recognize the name of the container and for that reason rejects the connection.

**Comment by emepetres** [comment]
I copy a docker compose files using version 3 that works without defining a new network, but it less secure than the proposed solution. Below is a more secure version defining the network.

**Less secure:**
```
version: '3.3'

services:
    idm_mysql:
        container_name: idm_data
        image: mysql/mysql-server:5.7.22
        restart: on-failure
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=idm
            - MYSQL_ROOT_HOST=idm
        volumes:
            - idm_data:/var/lib/mysql
    idm:
        container_name: idm
        image: fiware/idm
        restart: on-failure
        links:
            - idm_mysql
        ports:
            - "3000:3000"
            - "443:443"
        environment:
            - DATABASE_HOST=idm_mysql

# Volumes
volumes:
    idm_data:
```
**More secure:**
```
version: '3.3'

services:
    idm_mysql:
        container_name: idm_data
        image: mysql/mysql-server:5.7.22
        restart: on-failure
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=idm
            - MYSQL_ROOT_HOST=172.18.1.6
        volumes:
            - idm_data:/var/lib/mysql
        networks:
            network:
                ipv4_address: 172.18.1.5

    idm:
        container_name: idm
        image: fiware/idm
        restart: on-failure
        ports:
            - "3000:3000"
            - "443:443"
        environment:
            - DATABASE_HOST=idm_mysql
        networks:
            network:
                ipv4_address: 172.18.1.6

# Volumes
volumes:
    idm_data:
    
networks:
    network:
        ipam:
            config:
                - subnet: 172.18.1.0/24
```
